Add friends likes
AleksanderYandexPracticum/java-filmorate pull request #3
Opened 2023-05-30 20:45 UTC by AleksanderYandexPracticum

ТЗ10

2023-05-31 15:52 UTC, SergeyUdalivshiysa requested changes
Александр, привет!

Почти все реализовано верно, но есть несколько моментов требующих исправления.

Жду доработок!

2023-05-31 15:52 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handle(final RuntimeException e) {
Этот метод подразумевает, что должно обрабатываться только NotFoundException, сейчас обрабатываются все RuntimeException, которые могу не иметь никакого отношения к 404й ошибке. 
Исправь этот нюанс, пожалуйста.

2023-05-31 15:52 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User getUserInService(HttpServletRequest request, @PathVariable("id") Long id) {
Все "InService" в названиях метода не нужны

2023-05-31 15:52 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();  // Храним id тех кто лайкнул
Лучше назвать, чтобы по названию переменной было понятно, что это id тех кто лайкнул, например, userIdsWhoLiked или likesUserId

2023-05-31 15:52 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/InMemoryFilmStorage.java
> +package ru.yandex.practicum.filmorate.storage.film.FilmStorage;
Пакеты FilmStorage и UserStorage лишние

2023-05-31 15:52 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService/FilmService.java
> +    public final InMemoryFilmStorage inMemoryFilmStorage;
Эта переменная должна быть приватной, чтобы к ней не было доступа из других частей приложения, это повысит надежность приложения. Методы в контроллере, которые напрямую обращаются к этому полю должны вызывать метод сервиса и уже сервис обращаеться к хранилищу.

Исправь аналогичный нюанс и для UserService, пожалуйста

2023-05-31 15:52 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/FilmStorage.java
> +public interface FilmStorage {
Необязательно:

FilmStorage и UserStorage очень похожи, можно сделать класс Storage, объединяющий код двух этих классов, используя дженерик <T> вместо Film или User. Недублирование кода считается хорошей практикой.

2023-05-31 15:52 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/FilmStorage.java
> +    public Film add(Film film);
В интерфейсах необязательно обозначать методы public, они и без этого будут public

2023-05-31 17:41 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handle(final RuntimeException e) {
Исправил

2023-05-31 17:46 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();  // Храним id тех кто лайкнул
Исправил

2023-05-31 17:48 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/FilmStorage.java
> +    public Film add(Film film);
Исправил

2023-05-31 17:55 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService/FilmService.java
> +    public final InMemoryFilmStorage inMemoryFilmStorage;
Исправил

2023-05-31 18:02 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage/InMemoryFilmStorage.java
> +package ru.yandex.practicum.filmorate.storage.film.FilmStorage;
Исправил

2023-06-01 08:24 UTC, SergeyUdalivshiysa requested changes
Необходимо доработать вызовы методов хранилища из контроллеров, контроллер не должен напрямую вызывать методы хранилища.

2023-06-01 08:24 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService/FilmService.java
> +import ru.yandex.practicum.filmorate.storage.FilmStorage;
пакеты FilmService и UserService лишние

2023-06-01 14:52 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService/FilmService.java
> +import ru.yandex.practicum.filmorate.storage.FilmStorage;
Исправил

2023-06-01 21:14 UTC, SergeyUdalivshiysa approved these changes
Тепер все супер

2023-06-02 13:27 UTC, merged