add DataBase
AleksanderYandexPracticum/java-filmorate pull request #4
Opened 2023-06-15 17:27 UTC by AleksanderYandexPracticum

2023-06-20 05:32 UTC, Mishcore reviewed
.

2023-06-20 05:32 UTC, Mishcore commented on src/main/resources/static/ED.jpg
1. Поле userIdWhoLiked_id в таблице Film подразумевает, что его ячейками будут списки id лайкнувших фильм пользователей, тогда как 1НФ требует, чтобы ячейки хранили атомарные значения;
2. Аналогично с полем friends_id таблицы User;
3. Поле rating таблицы Film можно декомпозировать в таблицу с идентификатором и именем рейтинга.
4. Не совсем ясна суть таблиц Genre и Name_genre. Достаточно одной таблицы genre, полями которой будут идентификатор и название жанра, где идентификатор - PK таблицы и FK таблицы Film.

2023-06-21 06:54 UTC, Mishcore commented on src/main/resources/static/ER_Diogramma.jpg
Ревью диаграммы БД проведено

2023-07-03 18:59 UTC, SergeyUdalivshiysa requested changes
Александр, привет!

Работа большая и непростая, ты неплохо справился, но есть вещи требующее исправления.

2023-07-03 18:59 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Не обязательно:
Хорошей практикой является разделение компонентов Spring на интерфейс и реализацию.

2023-07-03 18:59 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/mpa/{id}")
Ендпоинты для mpa и жанров необходимо вынести в отдельные контроллеры. Не стоит смешивать логику разных сущностей в одном классе.

2023-07-03 18:59 UTC, SergeyUdalivshiysa commented on src/main/resources/schema.sql
> +confirmation int
Тут лучше boolean

2023-07-03 18:59 UTC, SergeyUdalivshiysa commented on src/main/resources/schema.sql
> +Create table IF NOT EXISTS friendships
Для друзей можно обойтись одной таблицей, со столбцам и user_id, friend_id и confirmation.

2023-07-03 18:59 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public LinkedHashMap<String, Object> getMpaById(HttpServletRequest request, @PathVariable("id") Integer id) {
Из ТЗ:
 // Пример возвращаемого значения
 {
   “id”: 1,
   “name”: “Комедия”
 }
 
 Для жанров и мпа тоже создай модель и возвращай ее. Возвращать вложенную структуру вроде  List<LinkedHashMap<String, Object>>  - плохая практика, всегда лучше ясная понятная модель.

2023-07-03 18:59 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs) throws SQLException {
Слишком большой метод, выполняющий много действий. Его необходимо разбить на методы. Привыкай делить логику на лаконичные методы.
Действия с базой данных связанные с mpa, лайками и жанрами надо выделить в отдельные методы DAO лайков, mpa и жанров, которые надо создать. Так код будет намного чище.

2023-07-04 17:39 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Уже есть

2023-07-04 17:39 UTC, AleksanderYandexPracticum commented on src/main/resources/schema.sql
> +confirmation int
Сделал

2023-07-04 17:39 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public LinkedHashMap<String, Object> getMpaById(HttpServletRequest request, @PathVariable("id") Integer id) {
Сделал

2023-07-04 17:39 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/mpa/{id}")
Сделал

2023-07-04 17:40 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    private Film makeFilm(ResultSet rs) throws SQLException {
Сделала

2023-07-04 17:40 UTC, AleksanderYandexPracticum commented on src/main/resources/schema.sql
> +Create table IF NOT EXISTS friendships
Сделал

2023-07-05 16:58 UTC, SergeyUdalivshiysa requested changes
Александр, привет!

Ты исправил все, кроме одного нюанса.

Жду доработок!

2023-07-05 16:58 UTC, SergeyUdalivshiysa commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Mpa> getAllMpa() {  // Возвращаю все название MPA
Писал об этом в прошлом ревью, но видимо не достаточно понятно. Методы взаимодействия с таблицами лайков, жанров, мпа и друзей стоит вынести в отдельные классы DAO. Не надо громоздить все в одном классе, это понижает читаемость, поддерживаемость и качество кода. Создай, пожалуйста GenreDbStorage, MpaDbStorage, а также, опционално, FriendDbStorage и LikeDbStorage. Вынеси туда методы взаимодействия с соответствующими таблицами, пожалуйста.

2023-07-05 17:54 UTC, AleksanderYandexPracticum commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +    public List<Mpa> getAllMpa() {  // Возвращаю все название MPA
Добавил GenreDbStorage, MpaDbStorage, FriendDbStorage и LikeDbStorage.

2023-07-06 16:41 UTC, SergeyUdalivshiysa approved these changes
Александр, привет!

Теперь все гуд, отличная работа!

2023-07-06 17:12 UTC, merged